#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Firefox='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Zathura state=tiled

#AutoStart
picom --experimental-backends &
feh --bg-fill ~/Pictures/Wallpapers/studio.png

#AutoFocus
bspc config focus_follows_pointer true
xsetroot -cursor_name left_ptr &

# Theming
# bash ~/.config/polybar/material/scripts/pywal.sh ~/Pictures/Wallpapers/color-waterfall.png  &
bash ~/.config/polybar/launch.sh --docky &
#bash ~/.config/polybar/material/scripts/pywal.sh ~/Pictures/Wallpapers/studio.png &
