#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Firefox='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Zathura state=tiled

#AutoStart
picom --experimental-backends &
#feh --bg-fill ~/Pictures/Wallpapers/studio.png
feh --bg-fill ~/Pictures/Wallpapers/NewWall.jpg

#AutoFocus
bspc config focus_follows_pointer true
xsetroot -cursor_name left_ptr &

# Theming
bspc config focused_border_color \#0A0918
bash ~/.config/polybar/launch.sh --docky &
